# Generated by Django 4.0.6 on 2022-07-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('picture', models.FileField(upload_to='')),
                ('author', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Amatuer', 'Amatuer'), ('Professional', 'Professional')], max_length=12)),
                ('votes', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
